spring:
  application:
    name: LethalFinance

  datasource:
    url: jdbc:postgresql://localhost:5435/lethalFinance
    driver-class-name: org.postgresql.Driver

  config:
    import: optional:application-local.yaml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration

server:
  port: 8080
